# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/snplib-fork

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/snplib-fork

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/snplib-fork/CMakeFiles /usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/snplib-fork/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code/snplib-fork/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _SNPLIB

# Build rule for target.
_SNPLIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _SNPLIB
.PHONY : _SNPLIB

# fast build rule for target.
_SNPLIB/fast:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/build
.PHONY : _SNPLIB/fast

src/adjusted_grm.o: src/adjusted_grm.cc.o

.PHONY : src/adjusted_grm.o

# target to build an object file
src/adjusted_grm.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/adjusted_grm.cc.o
.PHONY : src/adjusted_grm.cc.o

src/adjusted_grm.i: src/adjusted_grm.cc.i

.PHONY : src/adjusted_grm.i

# target to preprocess a source file
src/adjusted_grm.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/adjusted_grm.cc.i
.PHONY : src/adjusted_grm.cc.i

src/adjusted_grm.s: src/adjusted_grm.cc.s

.PHONY : src/adjusted_grm.s

# target to generate assembly for a file
src/adjusted_grm.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/adjusted_grm.cc.s
.PHONY : src/adjusted_grm.cc.s

src/data_manage.o: src/data_manage.cc.o

.PHONY : src/data_manage.o

# target to build an object file
src/data_manage.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/data_manage.cc.o
.PHONY : src/data_manage.cc.o

src/data_manage.i: src/data_manage.cc.i

.PHONY : src/data_manage.i

# target to preprocess a source file
src/data_manage.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/data_manage.cc.i
.PHONY : src/data_manage.cc.i

src/data_manage.s: src/data_manage.cc.s

.PHONY : src/data_manage.s

# target to generate assembly for a file
src/data_manage.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/data_manage.cc.s
.PHONY : src/data_manage.cc.s

src/genetic_variances.o: src/genetic_variances.cc.o

.PHONY : src/genetic_variances.o

# target to build an object file
src/genetic_variances.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/genetic_variances.cc.o
.PHONY : src/genetic_variances.cc.o

src/genetic_variances.i: src/genetic_variances.cc.i

.PHONY : src/genetic_variances.i

# target to preprocess a source file
src/genetic_variances.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/genetic_variances.cc.i
.PHONY : src/genetic_variances.cc.i

src/genetic_variances.s: src/genetic_variances.cc.s

.PHONY : src/genetic_variances.s

# target to generate assembly for a file
src/genetic_variances.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/genetic_variances.cc.s
.PHONY : src/genetic_variances.cc.s

src/grm.o: src/grm.cc.o

.PHONY : src/grm.o

# target to build an object file
src/grm.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/grm.cc.o
.PHONY : src/grm.cc.o

src/grm.i: src/grm.cc.i

.PHONY : src/grm.i

# target to preprocess a source file
src/grm.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/grm.cc.i
.PHONY : src/grm.cc.i

src/grm.s: src/grm.cc.s

.PHONY : src/grm.s

# target to generate assembly for a file
src/grm.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/grm.cc.s
.PHONY : src/grm.cc.s

src/gwas.o: src/gwas.cc.o

.PHONY : src/gwas.o

# target to build an object file
src/gwas.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/gwas.cc.o
.PHONY : src/gwas.cc.o

src/gwas.i: src/gwas.cc.i

.PHONY : src/gwas.i

# target to preprocess a source file
src/gwas.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/gwas.cc.i
.PHONY : src/gwas.cc.i

src/gwas.s: src/gwas.cc.s

.PHONY : src/gwas.s

# target to generate assembly for a file
src/gwas.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/gwas.cc.s
.PHONY : src/gwas.cc.s

src/ibs.o: src/ibs.cc.o

.PHONY : src/ibs.o

# target to build an object file
src/ibs.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/ibs.cc.o
.PHONY : src/ibs.cc.o

src/ibs.i: src/ibs.cc.i

.PHONY : src/ibs.i

# target to preprocess a source file
src/ibs.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/ibs.cc.i
.PHONY : src/ibs.cc.i

src/ibs.s: src/ibs.cc.s

.PHONY : src/ibs.s

# target to generate assembly for a file
src/ibs.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/ibs.cc.s
.PHONY : src/ibs.cc.s

src/king.o: src/king.cc.o

.PHONY : src/king.o

# target to build an object file
src/king.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/king.cc.o
.PHONY : src/king.cc.o

src/king.i: src/king.cc.i

.PHONY : src/king.i

# target to preprocess a source file
src/king.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/king.cc.i
.PHONY : src/king.cc.i

src/king.s: src/king.cc.s

.PHONY : src/king.s

# target to generate assembly for a file
src/king.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/king.cc.s
.PHONY : src/king.cc.s

src/multi_lmm.o: src/multi_lmm.cc.o

.PHONY : src/multi_lmm.o

# target to build an object file
src/multi_lmm.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/multi_lmm.cc.o
.PHONY : src/multi_lmm.cc.o

src/multi_lmm.i: src/multi_lmm.cc.i

.PHONY : src/multi_lmm.i

# target to preprocess a source file
src/multi_lmm.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/multi_lmm.cc.i
.PHONY : src/multi_lmm.cc.i

src/multi_lmm.s: src/multi_lmm.cc.s

.PHONY : src/multi_lmm.s

# target to generate assembly for a file
src/multi_lmm.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/multi_lmm.cc.s
.PHONY : src/multi_lmm.cc.s

src/python_wrapper.o: src/python_wrapper.cc.o

.PHONY : src/python_wrapper.o

# target to build an object file
src/python_wrapper.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/python_wrapper.cc.o
.PHONY : src/python_wrapper.cc.o

src/python_wrapper.i: src/python_wrapper.cc.i

.PHONY : src/python_wrapper.i

# target to preprocess a source file
src/python_wrapper.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/python_wrapper.cc.i
.PHONY : src/python_wrapper.cc.i

src/python_wrapper.s: src/python_wrapper.cc.s

.PHONY : src/python_wrapper.s

# target to generate assembly for a file
src/python_wrapper.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/python_wrapper.cc.s
.PHONY : src/python_wrapper.cc.s

src/simulations.o: src/simulations.cc.o

.PHONY : src/simulations.o

# target to build an object file
src/simulations.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/simulations.cc.o
.PHONY : src/simulations.cc.o

src/simulations.i: src/simulations.cc.i

.PHONY : src/simulations.i

# target to preprocess a source file
src/simulations.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/simulations.cc.i
.PHONY : src/simulations.cc.i

src/simulations.s: src/simulations.cc.s

.PHONY : src/simulations.s

# target to generate assembly for a file
src/simulations.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/simulations.cc.s
.PHONY : src/simulations.cc.s

src/snp.o: src/snp.cc.o

.PHONY : src/snp.o

# target to build an object file
src/snp.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/snp.cc.o
.PHONY : src/snp.cc.o

src/snp.i: src/snp.cc.i

.PHONY : src/snp.i

# target to preprocess a source file
src/snp.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/snp.cc.i
.PHONY : src/snp.cc.i

src/snp.s: src/snp.cc.s

.PHONY : src/snp.s

# target to generate assembly for a file
src/snp.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/snp.cc.s
.PHONY : src/snp.cc.s

src/statistics.o: src/statistics.cc.o

.PHONY : src/statistics.o

# target to build an object file
src/statistics.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/statistics.cc.o
.PHONY : src/statistics.cc.o

src/statistics.i: src/statistics.cc.i

.PHONY : src/statistics.i

# target to preprocess a source file
src/statistics.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/statistics.cc.i
.PHONY : src/statistics.cc.i

src/statistics.s: src/statistics.cc.s

.PHONY : src/statistics.s

# target to generate assembly for a file
src/statistics.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/statistics.cc.s
.PHONY : src/statistics.cc.s

src/ugrm.o: src/ugrm.cc.o

.PHONY : src/ugrm.o

# target to build an object file
src/ugrm.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/ugrm.cc.o
.PHONY : src/ugrm.cc.o

src/ugrm.i: src/ugrm.cc.i

.PHONY : src/ugrm.i

# target to preprocess a source file
src/ugrm.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/ugrm.cc.i
.PHONY : src/ugrm.cc.i

src/ugrm.s: src/ugrm.cc.s

.PHONY : src/ugrm.s

# target to generate assembly for a file
src/ugrm.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/ugrm.cc.s
.PHONY : src/ugrm.cc.s

src/uni_lmm.o: src/uni_lmm.cc.o

.PHONY : src/uni_lmm.o

# target to build an object file
src/uni_lmm.cc.o:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/uni_lmm.cc.o
.PHONY : src/uni_lmm.cc.o

src/uni_lmm.i: src/uni_lmm.cc.i

.PHONY : src/uni_lmm.i

# target to preprocess a source file
src/uni_lmm.cc.i:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/uni_lmm.cc.i
.PHONY : src/uni_lmm.cc.i

src/uni_lmm.s: src/uni_lmm.cc.s

.PHONY : src/uni_lmm.s

# target to generate assembly for a file
src/uni_lmm.cc.s:
	$(MAKE) -f CMakeFiles/_SNPLIB.dir/build.make CMakeFiles/_SNPLIB.dir/src/uni_lmm.cc.s
.PHONY : src/uni_lmm.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... _SNPLIB"
	@echo "... edit_cache"
	@echo "... src/adjusted_grm.o"
	@echo "... src/adjusted_grm.i"
	@echo "... src/adjusted_grm.s"
	@echo "... src/data_manage.o"
	@echo "... src/data_manage.i"
	@echo "... src/data_manage.s"
	@echo "... src/genetic_variances.o"
	@echo "... src/genetic_variances.i"
	@echo "... src/genetic_variances.s"
	@echo "... src/grm.o"
	@echo "... src/grm.i"
	@echo "... src/grm.s"
	@echo "... src/gwas.o"
	@echo "... src/gwas.i"
	@echo "... src/gwas.s"
	@echo "... src/ibs.o"
	@echo "... src/ibs.i"
	@echo "... src/ibs.s"
	@echo "... src/king.o"
	@echo "... src/king.i"
	@echo "... src/king.s"
	@echo "... src/multi_lmm.o"
	@echo "... src/multi_lmm.i"
	@echo "... src/multi_lmm.s"
	@echo "... src/python_wrapper.o"
	@echo "... src/python_wrapper.i"
	@echo "... src/python_wrapper.s"
	@echo "... src/simulations.o"
	@echo "... src/simulations.i"
	@echo "... src/simulations.s"
	@echo "... src/snp.o"
	@echo "... src/snp.i"
	@echo "... src/snp.s"
	@echo "... src/statistics.o"
	@echo "... src/statistics.i"
	@echo "... src/statistics.s"
	@echo "... src/ugrm.o"
	@echo "... src/ugrm.i"
	@echo "... src/ugrm.s"
	@echo "... src/uni_lmm.o"
	@echo "... src/uni_lmm.i"
	@echo "... src/uni_lmm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

